name: Test Docker Image

on:
  workflow_dispatch:

jobs:
  gradle:
    name: Gradle
    uses: anfanik/aru-workflow/.github/workflows/gradle.yml@main

    permissions:
      contents: write

    with:
      jdk_version: 21
      jdk_distribution: zulu

  docker:
    name: Docker
    uses: anfanik/aru-workflow/.github/workflows/docker.yml@main

    permissions:
      contents: write

    with:
      image_name: test-image
      image_version: 1.0

      publish_image: true
      publish_image_registry: ghcr.io/anfanik
    secrets:
      publish_image_registry_token: ${{ secrets.GITHUB_TOKEN }}
