name: Test Docker Image

on:
  workflow_dispatch:

jobs:
  docker-image:
    name: Docker
    uses: ./.github/workflows/docker-image.yml

    permissions:
      contents: write
      packages: write

    with:
      image_name: test-image
      image_version: 1.0

      publish_image: true
      publish_image_registry: ghcr.io/anfanik
      publish_image_github_packages: true
    secrets:
      publish_image_registry_token: ${{ secrets.GITHUB_TOKEN }}
