name: Test Docker Image

on:
  workflow_dispatch:

jobs:
  docker-image:
    uses: ./.github/workflows/docker-image.yml
    with:
      image_name: test-image
      image_version: 1.0
      publish_image_registry: ghcr.io/anfanik
      publish_image_registry_token: ${{ secrets.GITHUB_TOKEN }}